#!/bin/sh

set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl stop home-notifications.service || true
    systemctl disable home-notifications.service || true
fi

exit 0
